# Generated by Django 5.0.1 on 2024-01-11 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
